import { useMutation, useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables, TablesInsert } from "@/integrations/supabase/types";
import { useCart, CartItem } from "./useCart";

export type Order = Tables<"orders">;
export type OrderItem = Tables<"order_items">;

interface CreateOrderInput {
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  deliveryType: "delivery" | "pickup";
  deliveryZoneId?: string;
  deliveryAddress?: string;
  deliveryInstructions?: string;
  deliveryDate?: string;
  deliveryTimeSlot?: string;
  pickupPointId?: string;
  recipientName?: string;
  recipientPhone?: string;
  giftMessage?: string;
  deliveryFee?: number;
}

export const useCreateOrder = () => {
  const { items, clearCart, getTotalPrice } = useCart();

  return useMutation({
    mutationFn: async (input: CreateOrderInput) => {
      const subtotal = getTotalPrice();
      const deliveryFee = input.deliveryFee || 0;
      const total = subtotal + deliveryFee;

      // Create the order
      const orderInsert: TablesInsert<"orders"> = {
        customer_name: input.customerName,
        customer_email: input.customerEmail,
        customer_phone: input.customerPhone,
        delivery_type: input.deliveryType,
        delivery_zone_id: input.deliveryZoneId || null,
        delivery_address: input.deliveryAddress || null,
        delivery_instructions: input.deliveryInstructions || null,
        delivery_date: input.deliveryDate || null,
        delivery_time_slot: input.deliveryTimeSlot || null,
        pickup_point_id: input.pickupPointId || null,
        recipient_name: input.recipientName || null,
        recipient_phone: input.recipientPhone || null,
        gift_message: input.giftMessage || null,
        subtotal,
        delivery_fee: deliveryFee,
        total,
        order_number: "", // Will be generated by trigger
      };

      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert(orderInsert)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems: TablesInsert<"order_items">[] = items.map((item: CartItem) => ({
        order_id: order.id,
        product_id: item.product.id,
        product_name: item.product.name,
        product_image: item.product.image_url,
        quantity: item.quantity,
        unit_price: item.product.price,
        total_price: item.product.price * item.quantity,
        variant_info: item.variantInfo || null,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      return order;
    },
  });
};

export const useInitiateMpesaPayment = () => {
  return useMutation({
    mutationFn: async ({ phone, amount, orderId }: { phone: string; amount: number; orderId: string }) => {
      const { data, error } = await supabase.functions.invoke("mpesa-stk-push", {
        body: { phone, amount, orderId },
      });

      if (error) throw error;
      return data;
    },
  });
};

export const useOrderByNumber = (orderNumber: string) => {
  return useQuery({
    queryKey: ["orders", orderNumber],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("orders")
        .select("*, order_items(*)")
        .eq("order_number", orderNumber)
        .maybeSingle();

      if (error) throw error;
      return data;
    },
    enabled: !!orderNumber,
  });
};
